<a href="https://colab.research.google.com/github/OshankAgrawal/Foundation-of-Data-Science/blob/main/PANDAS_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# EXERCISE

**Question 01:- Write a Pandas program to create a dataframe from a dictionary and display it.**

Sample data: {&#39;X&#39;:[78,85,96,80,86], &#39;Y&#39;:[84,94,89,83,86],&#39;Z&#39;:[86,97,96,72,83]}

Answer

In [ ]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]})
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


About **pd.DataFrame()**

Raference Link: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html

**Question 02:- Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.**

Sample Python dictionary data and list labels:

exam_data = {&#39;name&#39;: [&#39;Anastasia&#39;, &#39;Dima&#39;, &#39;Katherine&#39;, &#39;James&#39;, &#39;Emily&#39;,
&#39;Michael&#39;, &#39;Matthew&#39;, &#39;Laura&#39;, &#39;Kevin&#39;, &#39;Jonas&#39;],
&#39;

score&#39;: [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
&#39;

attempts&#39;: [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
&#39;

qualify&#39;: [&#39;yes&#39;, &#39;no&#39;, &#39;yes&#39;, &#39;no&#39;, &#39;no&#39;, &#39;yes&#39;, &#39;yes&#39;, &#39;no&#39;, &#39;no&#39;, &#39;yes&#39;]}

labels = [&#39;a&#39;, &#39;b&#39;, &#39;c&#39;, &#39;d&#39;, &#39;e&#39;, &#39;f&#39;, &#39;g&#39;, &#39;h&#39;, &#39;i&#39;, &#39;j&#39;]

In [1]:
import pandas as pd
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, 54, 9, 20, 14.5, 65, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
df = pd.DataFrame(exam_data, index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   54.0         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura   65.0         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


About **pd.DataFrame()**

Reference Link: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html



**Question 03:- Write a Pandas program to get the first 3 rows of a given DataFrame.**

Sample Python dictionary data and list labels:

data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily','Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


**Method 1**

In [2]:
import pandas as pd
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, 54, 9, 20, 14.5, 65, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
df = pd.DataFrame(exam_data, index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print("Print first three rows od data..")
print(df.head(3))

Print first three rows od data..
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


**Method 2**

In [65]:
import pandas as pd
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, 54, 9, 20, 14.5, 65, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
df = pd.DataFrame(exam_data, index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print("Print first three rows od data..")
print(df.iloc[0:3])

Print first three rows od data..
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


**Question 04:- Write a Pandas program to select the &#39;name&#39; and &#39;score&#39; columns from the following DataFrame.**


Sample Python dictionary data and list labels:

data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily','Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [3]:
import pandas as pd
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, 54, 9, 20, 14.5, 65, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
df = pd.DataFrame(exam_data, index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print(df[['name','score']])

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James   54.0
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura   65.0
i      Kevin    8.0
j      Jonas   19.0


**Qestion 05:- Write a Pandas program to select the rows where the number of attempts in the examination is greater than 2.**

Sample Python dictionary data and list labels:

data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily','Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [5]:
import pandas as pd
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, 54, 9, 20, 14.5, 65, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
df = pd.DataFrame(exam_data, index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print(df[df['attempts']>2])

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James   54.0         3      no
f  Michael   20.0         3     yes


**Question 06:- Write a Pandas program to select the rows where the score is missing, i.e. is NaN.**

Sample Python dictionary data and list labels:

data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily','Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [12]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
df = pd.DataFrame(exam_data, index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print(df[df['score'].isnull()])


    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no


**Question 07:- Write a Pandas program to calculate the mean of all students&#39; scores. Data is stored in a dataframe.**

Sample Python dictionary data and list labels:

data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily','Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [16]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
df = pd.DataFrame(exam_data, index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print('Mean score for each different student in data frame: ')
print(df['score'].mean())

Mean score for each different student in data frame: 
13.5625


**Question 08:- Write a Pandas program to join the two given dataframes along rows and assign all data.**

**Test Data:**

student_data1={'student_id':['s1','s2','s3','s4','s5'], 'name':['Danniella Fenton','Ryder Storey','Bryce Jensen','Ed Bernal','Kwame Morin'], 'marks':[200,210,190,222,199]}

student_data2={'student_id':['s4','s5','s6','s7','s8'], 'name':['Scarlette Fisher','Carla Williamson','Dante Morse','Kaiser William','Madeeha Preston'], 'marks':[210,200,198,219,201]}

**Method 1**

In [25]:
import pandas as pd
student_data1={'student_id':['s1','s2','s3','s4','s5'], 'name':['Danniella Fenton','Ryder Storey','Bryce Jensen','Ed Bernal','Kwame Morin'], 'marks':[200,210,190,222,199]}

student_data2={'student_id':['s4','s5','s6','s7','s8'], 'Name':['Scarlette Fisher','Carla Williamson','Dante Morse','Kaiser William','Madeeha Preston'], 'marks':[210,200,198,219,201]}

df1=pd.DataFrame(student_data1)
df2=pd.DataFrame(student_data2)
print("Student Data 1: ")
print(df1,end='\n\n')
print("Student Data 2: ")
print(df2,end='\n\n')

frames = [df2, df1]

result = pd.concat(frames,ignore_index=True)
print("Resultant joint both DataFrames: ")
print(result)

Student Data 1: 
  student_id              name  marks
0         s1  Danniella Fenton    200
1         s2      Ryder Storey    210
2         s3      Bryce Jensen    190
3         s4         Ed Bernal    222
4         s5       Kwame Morin    199

Student Data 2: 
  student_id              Name  marks
0         s4  Scarlette Fisher    210
1         s5  Carla Williamson    200
2         s6       Dante Morse    198
3         s7    Kaiser William    219
4         s8   Madeeha Preston    201

Resultant joint both DataFrames: 
  student_id              Name  marks              name
0         s4  Scarlette Fisher    210               NaN
1         s5  Carla Williamson    200               NaN
2         s6       Dante Morse    198               NaN
3         s7    Kaiser William    219               NaN
4         s8   Madeeha Preston    201               NaN
5         s1               NaN    200  Danniella Fenton
6         s2               NaN    210      Ryder Storey
7         s3              

**Method 2**

In [35]:
import pandas as pd
student_data1={'student_id':['s1','s2','s3','s4','s5'], 'name':['Danniella Fenton','Ryder Storey','Bryce Jensen','Ed Bernal','Kwame Morin'], 'marks':[200,210,190,222,199]}

student_data2={'student_id':['s4','s5','s6','s7','s8'], 'Name':['Scarlette Fisher','Carla Williamson','Dante Morse','Kaiser William','Madeeha Preston'], 'marks':[210,200,198,219,201]}

df1=pd.DataFrame(student_data1)
df2=pd.DataFrame(student_data2)
print("Student Data 1: ")
print(df1,end='\n\n')
print("Student Data 2: ")
print(df2,end='\n\n')

result = df1.append(df2)
print("Resultant joint both DataFrames: ")
print(result)

Student Data 1: 
  student_id              name  marks
0         s1  Danniella Fenton    200
1         s2      Ryder Storey    210
2         s3      Bryce Jensen    190
3         s4         Ed Bernal    222
4         s5       Kwame Morin    199

Student Data 2: 
  student_id              Name  marks
0         s4  Scarlette Fisher    210
1         s5  Carla Williamson    200
2         s6       Dante Morse    198
3         s7    Kaiser William    219
4         s8   Madeeha Preston    201

Resultant joint both DataFrames: 
  student_id              name  marks              Name
0         s1  Danniella Fenton    200               NaN
1         s2      Ryder Storey    210               NaN
2         s3      Bryce Jensen    190               NaN
3         s4         Ed Bernal    222               NaN
4         s5       Kwame Morin    199               NaN
0         s4               NaN    210  Scarlette Fisher
1         s5               NaN    200  Carla Williamson
2         s6              

<ipython-input-35-db1c092dbf01>:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result = df1.append(df2)


Method 2 Generate warning says use method 1, may be it is possible that method 2 will be removed from pandas in future version.

**Question 09:- Write a Pandas program to join the two given dataframes along columns and assign all data.**

**Test Data:**

student_data1={'student_id':['s1','s2','s3','s4','s5'], 'name':['Danniella Fenton','Ryder Storey','Bryce Jensen','Ed Bernal','Kwame Morin'], 'marks':[200,210,190,222,199]}

student_data2={'student_id':['s4','s5','s6','s7','s8'], 'name':['Scarlette Fisher','Carla Williamson','Dante Morse','Kaiser William','Madeeha Preston'], 'marks':[210,200,198,219,201]}

In [28]:
import pandas as pd
student_data1={'student_id':['s1','s2','s3','s4','s5'], 'name':['Danniella Fenton','Ryder Storey','Bryce Jensen','Ed Bernal','Kwame Morin'], 'marks':[200,210,190,222,199]}

student_data2={'student_id':['s4','s5','s6','s7','s8'], 'name':['Scarlette Fisher','Carla Williamson','Dante Morse','Kaiser William','Madeeha Preston'], 'marks':[210,200,198,219,201]}

df1=pd.DataFrame(student_data1)
df2=pd.DataFrame(student_data2)
print("Student Data 1: ")
print(df1,end='\n\n')
print("Student Data 2: ")
print(df2,end='\n\n')

frames = [df1, df2]

result = pd.concat(frames,axis=1,join='inner',ignore_index=False)
print("Resultant joint both DataFrames: ")
print(result)

Student Data 1: 
  student_id              name  marks
0         s1  Danniella Fenton    200
1         s2      Ryder Storey    210
2         s3      Bryce Jensen    190
3         s4         Ed Bernal    222
4         s5       Kwame Morin    199

Student Data 2: 
  student_id              name  marks
0         s4  Scarlette Fisher    210
1         s5  Carla Williamson    200
2         s6       Dante Morse    198
3         s7    Kaiser William    219
4         s8   Madeeha Preston    201

Resultant joint both DataFrames: 
    0                 1    2   3                 4    5
0  s1  Danniella Fenton  200  s4  Scarlette Fisher  210
1  s2      Ryder Storey  210  s5  Carla Williamson  200
2  s3      Bryce Jensen  190  s6       Dante Morse  198
3  s4         Ed Bernal  222  s7    Kaiser William  219
4  s5       Kwame Morin  199  s8   Madeeha Preston  201


About **pd.concat()**

Refrence Link: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html

attributes:

1. List of DataFrames which is concatenated. (Order of list is matter, first element of list comes first)

2. **axis**: (by default its value is '0')

* if '1' concatenate along columns

* if '0' concatnate along rows

3. **ignore_index:** It is boolean **By default** its value is **False**

its role depend on the **axis** attribute

* if **axis=0** than forwarded index means number of rows comes in a sequence

* if **axis=1** than it forget the name of columns and gives a sequence to them

One of the interesting thing of this function is

* if **axis=0** in this case DataFrames is concatnate along rows means data of second DataFrame is comes below the other. if the the colummn name is same than there is no problem, if any of one column name is different than it is treated as different column and in the other DataFrame the value of that column is **NaN** otherwise data is comes after the other, and the column name remains unchanged.

* if **axis=1** in this case DataFrames is concatenate along columns means data of second DataFrame is comes in side the other means number of columns is increased weather the column name is same or different does't matter.

**Question 10:-Write a Pandas program to append rows to an existing DataFrame and display the combined data.**

**Test Data:**

student_data1={'student_id':['s1','s2','s3','s4','s5'], 'name':['Danniella Fenton','Ryder Storey','Bryce Jensen','Ed Bernal','Kwame Morin'], 'marks':[200,210,190,222,199]}

New Row(s)

student_data={'student_id' : 's6', 'name' : 'Scralette Fisher', 'marks' : 205}

**Method 1**

In [34]:
import pandas as pd
student_data1={'student_id':['s1','s2','s3','s4','s5'], 'name':['Danniella Fenton','Ryder Storey','Bryce Jensen','Ed Bernal','Kwame Morin'], 'marks':[200,210,190,222,199]}

student_data={'student_id' : ['s6'], 'name' : ['Scralette Fisher'], 'marks' : [205]}
df1=pd.DataFrame(student_data1)
df2=pd.DataFrame(student_data)
print("Student Data 1: ")
print(df1,end='\n\n')
print("Student Data 2: ")
print(df2,end='\n\n')

frames = [df2, df1]

result = pd.concat(frames,ignore_index=True)
print("Resultant joint both DataFrames: ")
print(result)

Student Data 1: 
  student_id              name  marks
0         s1  Danniella Fenton    200
1         s2      Ryder Storey    210
2         s3      Bryce Jensen    190
3         s4         Ed Bernal    222
4         s5       Kwame Morin    199

Student Data 2: 
  student_id              name  marks
0         s6  Scralette Fisher    205

Resultant joint both DataFrames: 
  student_id              name  marks
0         s6  Scralette Fisher    205
1         s1  Danniella Fenton    200
2         s2      Ryder Storey    210
3         s3      Bryce Jensen    190
4         s4         Ed Bernal    222
5         s5       Kwame Morin    199


**Method 2**

In [36]:
import pandas as pd
student_data1={'student_id':['s1','s2','s3','s4','s5'], 'name':['Danniella Fenton','Ryder Storey','Bryce Jensen','Ed Bernal','Kwame Morin'], 'marks':[200,210,190,222,199]}

student_data={'student_id' : ['s6'], 'name' : ['Scralette Fisher'], 'marks' : [205]}
df=pd.DataFrame(student_data1)

print("Student Data 1: ")
print(df,end='\n\n')

student_data={'student_id' : 's6', 'name' : 'Scralette Fisher', 'marks' : 205}

result = df.append(student_data,ignore_index=True)
print(result)

Student Data 1: 
  student_id              name  marks
0         s1  Danniella Fenton    200
1         s2      Ryder Storey    210
2         s3      Bryce Jensen    190
3         s4         Ed Bernal    222
4         s5       Kwame Morin    199

  student_id              name  marks
0         s1  Danniella Fenton    200
1         s2      Ryder Storey    210
2         s3      Bryce Jensen    190
3         s4         Ed Bernal    222
4         s5       Kwame Morin    199
5         s6  Scralette Fisher    205


<ipython-input-36-baf3eb9f532f>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result = df.append(student_data,ignore_index=True)


Method 2 Generate warning says use method 1, may be it is possible that method 2 will be removed from pandas in future version.

**Question 11:- Write a Pandas program to display the dimensions of the World alcohol consumption dataset.**

**Test Data:**

test_data = {'year':[1986,1986,1985,1986,1987], 'WHO region':['Western Pacific','Americas','Africa','Americas','Americas'], 'Country':['Viet Nam','Uruguay',"Cte d'Ivoier",'Colombia','Saint Kitts and Nevis'], 'Types':['Wine','Other','Wine','Beer','Beer'], 'Display_Values':[0.00,0.50,1.62,4.27,1.98]}


In [39]:
import pandas as pd

test_data = {'year':[1986,1986,1985,1986,1987], 'WHO region':['Western Pacific','Americas','Africa','Americas','Americas'], 'Country':['Viet Nam','Uruguay',"Cte d'Ivoier",'Colombia','Saint Kitts and Nevis'], 'Types':['Wine','Other','Wine','Beer','Beer'], 'Display_Values':[0.00,0.50,1.62,4.27,1.98]}

df = pd.DataFrame(test_data)
print(df,end='\n\n')

print("Dimension of DataFrame: ", df.ndim)

   year       WHO region                Country  Types  Display_Values
0  1986  Western Pacific               Viet Nam   Wine            0.00
1  1986         Americas                Uruguay  Other            0.50
2  1985           Africa           Cte d'Ivoier   Wine            1.62
3  1986         Americas               Colombia   Beer            4.27
4  1987         Americas  Saint Kitts and Nevis   Beer            1.98

Dimension of DataFrame:  2


About **pandas.DataFrame.ndim**

Refrence Link: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.ndim.html

This function Return an int representing the number of axes / array dimensions.

Return 1 if Series. Otherwise return 2 if DataFrame.

**Question 12:- Write a Pandas program to display the shape of the World alcohol consumption dataset. Also extract the column names from the dataset.**

**Test Data:**

test_data = {'year':[1986,1986,1985,1986,1987], 'WHO region':['Western Pacific','Americas','Africa','Americas','Americas'], 'Country':['Viet Nam','Uruguay',"Cte d'Ivoier",'Colombia','Saint Kitts and Nevis'], 'Types':['Wine','Other','Wine','Beer','Beer'], 'Display_Values':[0.00,0.50,1.62,4.27,1.98]}


In [40]:
import pandas as pd

test_data = {'year':[1986,1986,1985,1986,1987], 'WHO region':['Western Pacific','Americas','Africa','Americas','Americas'], 'Country':['Viet Nam','Uruguay',"Cte d'Ivoier",'Colombia','Saint Kitts and Nevis'], 'Types':['Wine','Other','Wine','Beer','Beer'], 'Display_Values':[0.00,0.50,1.62,4.27,1.98]}

df = pd.DataFrame(test_data)
print(df,end='\n\n')

print("Shape of DataFrame: ",df.shape)

   year       WHO region                Country  Types  Display_Values
0  1986  Western Pacific               Viet Nam   Wine            0.00
1  1986         Americas                Uruguay  Other            0.50
2  1985           Africa           Cte d'Ivoier   Wine            1.62
3  1986         Americas               Colombia   Beer            4.27
4  1987         Americas  Saint Kitts and Nevis   Beer            1.98

Shape of DataFrame:  (5, 5)


About **Pandas.DataFrame.shape**

Reference Link: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.shape.html

This function Return a tuple representing the dimensionality of the DataFrame.

**Question 13:- Write a Pandas program to display the size of the World alcohol consumption dataset.**

**Test Data:**

test_data = {'year':[1986,1986,1985,1986,1987], 'WHO region':['Western Pacific','Americas','Africa','Americas','Americas'], 'Country':['Viet Nam','Uruguay',"Cte d'Ivoier",'Colombia','Saint Kitts and Nevis'], 'Types':['Wine','Other','Wine','Beer','Beer'], 'Display_Values':[0.00,0.50,1.62,4.27,1.98]}


In [41]:
import pandas as pd

test_data = {'year':[1986,1986,1985,1986,1987], 'WHO region':['Western Pacific','Americas','Africa','Americas','Americas'], 'Country':['Viet Nam','Uruguay',"Cte d'Ivoier",'Colombia','Saint Kitts and Nevis'], 'Types':['Wine','Other','Wine','Beer','Beer'], 'Display_Values':[0.00,0.50,1.62,4.27,1.98]}

df = pd.DataFrame(test_data)
print(df,end='\n\n')

print("Size of DataFrame: ",df.size)

   year       WHO region                Country  Types  Display_Values
0  1986  Western Pacific               Viet Nam   Wine            0.00
1  1986         Americas                Uruguay  Other            0.50
2  1985           Africa           Cte d'Ivoier   Wine            1.62
3  1986         Americas               Colombia   Beer            4.27
4  1987         Americas  Saint Kitts and Nevis   Beer            1.98

Size of DataFrame:  25


About **pandas.DataFrame.size**

Refrence Link: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.size.html

This function Return an int representing the number of elements in this object.

Return the number of rows if Series. Otherwise return the number of rows times number of columns if DataFrame.

**Question 14:- Write a Pandas program to extract the column names from the dataset.**

**Test Data:**

test_data = {'year':[1986,1986,1985,1986,1987], 'WHO region':['Western Pacific','Americas','Africa','Americas','Americas'], 'Country':['Viet Nam','Uruguay',"Cte d'Ivoier",'Colombia','Saint Kitts and Nevis'], 'Types':['Wine','Other','Wine','Beer','Beer'], 'Display_Values':[0.00,0.50,1.62,4.27,1.98]}


In [60]:
import pandas as pd

test_data = {'year':[1986,1986,1985,1986,1987], 'WHO region':['Western Pacific','Americas','Africa','Americas','Americas'], 'Country':['Viet Nam','Uruguay',"Cte d'Ivoier",'Colombia','Saint Kitts and Nevis'], 'Types':['Wine','Other','Wine','Beer','Beer'], 'Display_Values':[0.00,0.50,1.62,4.27,1.98]}

df = pd.DataFrame(test_data)
print(df,end='\n\n')
print("Method 1: ")
print("Name of columns: ")
print(list(df.columns))
print()
print("Method 2: ")
print("Name of columns: ")
print(df.keys())
print()
print("Method 3: ")
print("Name of columns: ")
print(df.columns.values)
print()
print("Method 4: ")
print("Name of columns: ")
print(df.columns.values.tolist())
print()
print("Method 5: ")
print("Name of columns: ")
print(sorted(df))
print()
print("Method 6: ")
print("Name of columns: ")
for col in df.columns:
    print(col)

   year       WHO region                Country  Types  Display_Values
0  1986  Western Pacific               Viet Nam   Wine            0.00
1  1986         Americas                Uruguay  Other            0.50
2  1985           Africa           Cte d'Ivoier   Wine            1.62
3  1986         Americas               Colombia   Beer            4.27
4  1987         Americas  Saint Kitts and Nevis   Beer            1.98

Method 1: 
Name of columns: 
['year', 'WHO region', 'Country', 'Types', 'Display_Values']

Method 2: 
Name of columns: 
Index(['year', 'WHO region', 'Country', 'Types', 'Display_Values'], dtype='object')

Method 3: 
Name of columns: 
['year' 'WHO region' 'Country' 'Types' 'Display_Values']

Method 4: 
Name of columns: 
['year', 'WHO region', 'Country', 'Types', 'Display_Values']

Method 5: 
Name of columns: 
['Country', 'Display_Values', 'Types', 'WHO region', 'year']

Method 6: 
Name of columns: 
year
WHO region
Country
Types
Display_Values


Reference Link of answer 14 :- https://www.geeksforgeeks.org/how-to-get-column-names-in-pandas-dataframe/